version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - .env  # Ensures the environment variables from .env are loaded
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 3

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env  # Ensure the FastAPI service gets the correct credentials
    ports:
      - "8000:8000"

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    depends_on:
      - fastapi
    env_file:
      - .env
    ports:
      - "8501:8501"

volumes:
  pgdata:
